services:
  Richardhj\ContaoAjaxReloadElementBundle\EventListener\AjaxReloadElementListener:
    arguments:
      - '@contao.image.picture_factory'
    public: true
  
  Richardhj\ContaoAjaxReloadElementBundle\EventListener\DataContanier\ModifyPalettesListener:
    public: true
